<?php

require_once dirname(__FILE__) . '/../Concat.php';

/**
 * Test class for Concat.
 * Generated by PHPUnit on 2012-01-04 at 22:55:28.
 */
class ConcatTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Concat
     */
    protected $concatObj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->concatObj = new Concat('../dictionary.txt');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testConcatPair() {
        $this->assertTrue($this->concatObj->checkWordPair('sein', 'er'));
    }
}

?>
